### ISSUE TITLE
Destro lock stat weights

### ISSUE THREAD

**Issue by GFRRULEZ** [Brusalk/destro-guide#9]
I know its still pretty early in 7.1.5 but was wondering what decent stat weights for us r....I have read many different people ideas on weights and they r all different; I know haste is still king then int crit vert and mastery. I use the PAWN addon for quick gear checks so am after some actually #'s
at the moment I'm going with 
Haste = 1.2
Int and crit = 1.0
Vert = 0.9
Mastery = 0.8
Thx!
PS: I know this is a change log but I thought this was applicable...sorry if that's not the case :)

**Comment by Brusalk** [comment]
Hey Man! 

I would check out the warlock discord -- The stat weights at this point are pretty fluid and change in a lot of situations. You'll be able to get a quick answer over there :)
